import React from "react";
import { motion } from "framer-motion";
const TfaVerificationFade = () => {
    return (
        {
            TfaVerificationInitial: {
                opacity: 0,
                x: -100, 
            },
            TfaVerificationAnimate :{
                opacity: 1,
                x: 0,
                transition : {
                    duration: 0.5,
                    ease: "easeInOut",
                    type: "spring",
                    stiffness: 100
                } 
            }
        }
    )
}
const TfaVerification = () =>{
    return(
        <motion.div
            variants={TfaVerificationFade()}
            initial="TfaVerificationInitial"
            animate="TfaVerificationAnimate"
            className="p-6 rounded-lg shadow-lg max-w-screen-sm lg:w-[600px] text-white flex flex-col gap-4 items-center"
        >
            <div className='  text-4xl font-semibold text-white tracking-wider mb-[50px] flex flex-col gap-4 justify-center items-center'>
                <h1 >Two Factor Authentication</h1>
                <p className='text-lg font-normal '>Enter The OTP generated by your Authenticator App</p>
            </div>
            <div className="flex gap-3 justify-center">
                {
                    [1,2,3,4,5,6].map((item, index) => {
                        return (
                            <input
                                type="text"
                                inputMode="numeric"
                                pattern="\d{1}"
                                key={index}
                                className="h-[40px] w-[40px] bg-transparent outline-none border-white border rounded-md text-center"/>
                        )
                    })
                }
            </div>
        </motion.div>
    )
}

export default TfaVerification