"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()

SECRET_KEY = os.getenv('DJANGO_SECRET')
OAUTH_API_KEY = os.getenv('DJANGO_API_KEY')
OAUTH_REDIRECT_URI = os.getenv('DJANGO_REDIRECT_URI')
OAUTH_CLIENT = os.getenv('DJANGO_CLIENT')
JWT_SECRET_KEY = os.getenv('DJANGO_JWT_SECRET_KEY')
ACCESS_TOKEN_LIFETIME = int(os.getenv('DJANGO_ACCESS_TOKEN_LIFETIME'))
REFRESH_TOKEN_LIFETIME = int(os.getenv('DJANGO_REFRESH_TOKEN_LIFETIME'))

DEBUG = False
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'channels',
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'users.apps.UsersConfig',
    'conversations.apps.ConversationsConfig',
    'status.apps.StatusConfig',
    'friendship.apps.FriendshipConfig',
    'game.apps.GameConfig',
]

AUTH_USER_MODEL = "users.MyUser"

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'users.utils.my_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.auth.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]


CORS_ALLOW_ALL_ORIGINS = False 
CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = (
    "https://10.11.6.2:4444",
    "https://10.11.6.2",
)


CORS_ALLOWED_ORIGINS = [
    "https://10.11.6.2:4444",
    "https://10.11.6.2",
]


CSRF_TRUSTED_ORIGINS = [
    "https://10.11.6.2:4444",
    "https://10.11.6.2",
]

CORS_ALLOW_CREDENTIALS = True

ASGI_APPLICATION = 'api.asgi.application'

CHANNEL_LAYERS ={
    'default':
    {
        'BACKEND' : 'channels_redis.core.RedisChannelLayer',
        'CONFIG':{
            "hosts" : [('redis', 6379)]
        }
    }
}

ROOT_URLCONF = 'api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'api.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = '/api/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static') 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

