FROM node:22

# install nginx packages
RUN apt-get update
RUN apt-get install -y nginx openssl

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . .
# nginx setup
COPY ./nginx/conf/default.conf /etc/nginx/conf.d/default.conf
RUN chmod +x script.prod.sh

CMD "./script.prod.sh"