services:
  postgres-db:
    image: postgres:13
    container_name: postgresql
    env_file:
      - .env
    restart: always
    networks:
      - transendence
    volumes:
      - psql:/var/lib/postgresql/data
  gunicorn_django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gunicorn_django
    command: > 
      sh -c "/bin/bash -c /wait_data_base.sh && /bin/bash -c /setup_backend.sh && gunicorn api.wsgi:application --bind 0.0.0.0:8000"
    restart: always
    volumes:
      - backend:/app
      - media:/app/media
    env_file:
      - .env
    networks:
      - transendence
    depends_on:
      - redis
  daphne_django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: daphne_django
    command: sh -c " /bin/bash -c /wait_data_base.sh && daphne -b 0.0.0.0 -p 8001 api.asgi:application"
    restart: always 
    volumes:
      - backend:/app
    env_file:
      - .env
    networks:
      - transendence
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart : always
    volumes:
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - daphne_django
      - gunicorn_django
    ports:
      - "4444:443"
    networks:
      - transendence
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - transendence
    depends_on:
      - postgres-db

networks:
  transendence:
    name: transendence

volumes:
  backend:
  media:
  psql:
