services:
  postgres-db:
    image: postgres:13
    container_name: postgresql
    env_file:
      - .env
    restart: always
    # WHY THIS PIORTS IS HERE ? (NO NEED FOR IT : HSAKTIWY QUESTION)
    ports:
      - "5432:5432"
    networks:
      - transendence
  gunicorn_django:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gunicorn_django
    command: > 
      sh -c "python manage.py makemigrations &&  python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn api.wsgi:application --bind 0.0.0.0:8000 --log-level debug --capture-output"
    restart: always
    # ports:
    #   - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - transendence
    depends_on:
      - redis
  daphne_django:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: daphne_django
    command: sh -c "daphne -b 0.0.0.0 -p 8001 api.asgi:application"
    restart: always
    # ports:
    #   - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - transendence
    depends_on:
      - redis
      # - daphne_django
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    restart : always
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    depends_on:
      - daphne_django
      - gunicorn_django
    networks:
      - transendence
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - transendence
    depends_on:
      - postgres-db
  nginx:
    build: nginx/.
    container_name: nginx
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/media:/app/media
      - ./backend/static:/app/static
    depends_on:
      - daphne_django
      - gunicorn_django
      - frontend
    ports:
      - "4444:443"
    networks:
      - transendence

networks:
  transendence:
    name: transendence