services:
  postgres-db:
    image: postgres:13
    container_name: postgresql
    env_file:
      - .env
    restart: always
    networks:
      - transendence
  gunicorn_django:
    build: backend/.
    container_name: gunicorn_django
    command: > 
      sh -c "  /bin/bash -c /script.sh &&  python manage.py makemigrations &&  python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn api.wsgi:application --bind 0.0.0.0:8000 --log-level debug --capture-output"
    restart: always
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - transendence
    depends_on:
      - redis
  daphne_django:
    build: backend/.
    container_name: daphne_django
    command: sh -c " /bin/bash -c /script.sh && daphne -b 0.0.0.0 -p 8001 api.asgi:application"
    restart: always 
    volumes:
      - ./backend:/app
    env_file:
      - .env
    networks:
      - transendence
    depends_on:
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    restart : always
    volumes:
      - ./frontend:/app
      - ./backend/media:/app/media
      - ./backend/static:/app/static
    env_file:
      - .env
    depends_on:
      - daphne_django
      - gunicorn_django
    ports:
      - "4444:443"
    networks:
      - transendence
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - transendence
    depends_on:
      - postgres-db

networks:
  transendence:
    name: transendence

