# Generated by Django 4.2.13 on 2024-07-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='id_user_fk',
            new_name='sender',
        ),
    ]
