# Generated by Django 4.2.13 on 2024-07-27 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_rename_id_user_fk_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
