# Generated by Django 4.2.13 on 2024-11-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_channel_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
