server{
    listen 443 ssl;
    client_max_body_size 5M;
    # ssl configuration
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    # Serve static files
    location /api/static/ {
        alias /app/static/;  # Path to STATIC_ROOT
    }
    # Serve media files
    location /api/media/ {
        alias /app/media/;  # Path to MEDIA_ROOT
    }
    # for http connection GUNICORN 
    location /api/ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://gunicorn_django:8000/;
        proxy_set_header Host $host;
    }

    # for websocket connection DAPHNE
    location /api/ws/ {
        rewrite ^/api(/.*)$ $1 break;
        proxy_pass http://daphne_django:8001/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    # Serve the React frontend
    location / {
        proxy_pass http://frontend:5173/;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}