# Generated by Django 4.2.13 on 2024-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('system', 'system'), ('friendship', 'friendship'), ('gameInvitation', 'gameInvitation'), ('tournament', 'tournament')], default='system', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('lostes', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
