# Generated by Django 4.2.13 on 2025-02-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIRST_MATCH', 'First Match'), ('WIN_STREAK', 'Winning Streak'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('LEGEND', 'Legend')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('game_numbers', models.IntegerField(default=0)),
                ('win_streak', models.IntegerField(default=0)),
                ('unlocked', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('system', 'system'), ('friendship', 'friendship'), ('gameInvitation', 'gameInvitation'), ('tournament', 'tournament'), ('message', 'message')], default='system', max_length=20)),
                ('channel_id', models.IntegerField(null=True)),
                ('friend_request_id', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_readed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField()),
                ('wins', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('_wins', models.IntegerField(default=0)),
                ('_lose', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
                ('level', models.FloatField(default=0)),
            ],
        ),
    ]
