# Generated by Django 4.2.13 on 2025-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('system', 'system'), ('friendship', 'friendship'), ('gameInvitation', 'gameInvitation'), ('tournament', 'tournament'), ('message', 'message')], default='system', max_length=20)),
                ('channel_id', models.IntegerField(null=True)),
                ('friend_request_id', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_readed', models.BooleanField(default=False)),
                ('room_name', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField()),
                ('wins', models.IntegerField(default=0)),
                ('lose', models.IntegerField(default=0)),
                ('_wins', models.IntegerField(default=0)),
                ('_lose', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
                ('xp', models.IntegerField(default=0)),
                ('level', models.FloatField(default=0.0)),
                ('last_match_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
