# Generated by Django 4.2.13 on 2024-07-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'system'), ('friendship', 'friendship'), ('gameInvitation', 'gameInvitation'), ('tournament', 'tournament')], default='system', max_length=20),
        ),
    ]
