# Generated by Django 4.2.13 on 2025-02-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='room_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
