# Generated by Django 4.2.13 on 2025-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='achievements',
            name='win_streak',
            field=models.IntegerField(default=0),
        ),
    ]
