# Generated by Django 4.2.13 on 2024-08-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_notification_is_readed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'system'), ('friendship', 'friendship'), ('gameInvitation', 'gameInvitation'), ('tournament', 'tournament'), ('message', 'message')], default='system', max_length=20),
        ),
    ]
