# Generated by Django 4.2.13 on 2024-10-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='friend_request_id',
            field=models.IntegerField(null=True),
        ),
    ]
