# Generated by Django 4.2.13 on 2025-01-17 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0005_notification_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestatus',
            name='level',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Acheivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
                ('id_user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
