FROM python:3.12-slim-bookworm
RUN apt-get update \
    && apt-get install -y \
       libpq-dev \
       gcc \
       netcat-openbsd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV DJANGO_LOG_LEVEL=INFO

COPY requirements.txt .
COPY ./utils/setup_backend.sh .
COPY ./utils/wait_data_base.sh .

RUN chmod +x setup_backend.sh wait_data_base.sh
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app
COPY . .
