FROM python:3.12-slim-bookworm
RUN apt-get update \
    && apt-get install -y \
       libpq-dev \
       gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]