# Generated by Django 4.2.13 on 2024-07-08 16:16

from django.db import migrations, models
import django.db.models.deletion
import friendship.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_secondnname_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPTED', 'accepted'), ('DECLINED', 'declined'), ('BLOCKED', 'blocked')], default=friendship.models.RelationShipStatus['PENDING'], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship', to='users.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'friend'], name='friendship__user_id_572c5f_idx')],
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
