# Generated by Django 4.2.13 on 2024-07-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_alter_friendship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('declined', 'DECLINED'), ('blocked', 'BLOCKED')], default='pending', max_length=100),
        ),
    ]
