# Generated by Django 4.2.13 on 2025-01-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHESS', 'CHESS'), ('PONG', 'PONG')], default='PONG', max_length=10)),
                ('score_p1', models.IntegerField(default=0)),
                ('score_p2', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'WAITING'), ('in_progress', 'IN_PROGRESS'), ('ended', 'ENDED')], default='waiting', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
