# Generated by Django 4.2.13 on 2024-07-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_player1_remove_game_player2_game_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
