# Generated by Django 4.2.13 on 2025-01-17 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_rename_start_game_time_remove_game_end_game_loser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='players',
        ),
        migrations.AddField(
            model_name='game',
            name='score_p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='score_p2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(choices=[('CHESS', 'CHESS'), ('PONG', 'PONG')], default='PONG', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='user_p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_p1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='user_p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_p2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
