# Generated by Django 4.2.13 on 2024-07-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'WAITING'), ('in_progress', 'IN_PROGRESS'), ('ended', 'ENDED')], default='waiting', max_length=20),
        ),
    ]
