# Generated by Django 4.2.13 on 2025-01-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_players_game_score_p1_game_score_p2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
    ]
