# Generated by Django 4.2.13 on 2024-07-18 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinvitation',
            name='user_receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameinvitation',
            name='user_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='gameinvitation',
            index=models.Index(fields=['user_sender', 'user_receiver'], name='invitation__user_se_35ed8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameinvitation',
            unique_together={('user_sender', 'user_receiver')},
        ),
    ]
