# Generated by Django 4.2.13 on 2024-07-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('secondnName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('two_factor_auth_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
