# Generated by Django 4.2.13 on 2025-02-07 10:54

import django.core.validators
from django.db import migrations, models
import pyotp
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('login', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-20 characters and can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]{3,20}$')])),
                ('firstName', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name should be 3-50 characters long and contain only letters and spaces.', regex="^(?=.{3,50}$)[A-Za-z]+([ '-][A-Za-z]+)*$")])),
                ('lastName', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name should be 3-50 characters long and contain only letters and spaces.', regex="^(?=.{3,50}$)[A-Za-z]+([ '-][A-Za-z]+)*$")])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator(message='It should be a valid email address!')], verbose_name='email address')),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('two_factor_auth_code', models.CharField(default=pyotp.random_base32, max_length=32)),
                ('profile_pic', models.ImageField(blank=True, default='default.jpeg', upload_to=users.models.user_pic_location, validators=[users.models.validateImage])),
                ('CoverProfile', models.ImageField(blank=True, default='default.jpeg', upload_to=users.models.user_pic_location)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('online', 'Online'), ('in_game', 'In Game'), ('in_search', 'In Search'), ('end_game', 'End Game'), ('already_in', 'Already In'), ('ready', 'Ready'), ('offline', 'Offline')], default='offline', max_length=20)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('oauth', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
