# Generated by Django 4.2.13 on 2024-07-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secondnName',
            new_name='lastName',
        ),
    ]
