# Generated by Django 4.2.13 on 2025-01-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
    ]
