# Generated by Django 4.2.13 on 2025-02-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='game_state',
            field=models.CharField(choices=[('online', 'Online'), ('in_game', 'In Game'), ('in_search', 'In Search'), ('end_game', 'End Game'), ('already_in', 'Already In'), ('ready', 'Ready'), ('offline', 'Offline')], default='online', max_length=20),
        ),
    ]
