# Generated by Django 4.2.13 on 2025-01-26 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='sessions',
        ),
        migrations.DeleteModel(
            name='USER_SESSIONS',
        ),
    ]
