# Generated by Django 4.2.13 on 2024-09-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthDay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
