# Generated by Django 4.2.13 on 2024-09-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_myuser_birthday_myuser_last_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='oauth',
            field=models.BooleanField(default=False),
        ),
    ]
