# Generated by Django 4.2.13 on 2024-12-24 18:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_myuser_two_factor_auth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to=users.models.user_pic_location, validators=[users.models.validateImage]),
        ),
    ]
