# Generated by Django 4.2.13 on 2024-12-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='login',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
