# Generated by Django 4.2.13 on 2024-12-27 14:29

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='CoverProfile',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to=users.models.user_pic_location, validators=[users.models.validateImage]),
        ),
    ]
