# Generated by Django 4.2.13 on 2024-12-27 16:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_myuser_coverprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='CoverProfile',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to=users.models.user_pic_location),
        ),
    ]
