# Generated by Django 4.2.13 on 2024-12-31 13:19

from django.db import migrations, models
import uuid

def generate_unique_ids(apps, schema_editor):
    MyModel = apps.get_model('users', 'myuser')
    for obj in MyModel.objects.all():
        obj.unique_id = uuid.uuid4()  # Assign a new unique UUID
        obj.save()
class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_myuser_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_unique_ids),
    ]
